(tested) Re-adds re-adding EMHs
DDMers/Deep-Space-13 pull request #10
Opened 2019-01-19 21:03 UTC by Kmc2000

:cl: Kmc2000
add: Added EMHs as a ghostrole. Call one in if you injure yourself and need a doctor.
/:cl:

2019-01-22 22:02 UTC, Jalleo submitted a review, later dismissed
See what I said below.

2019-01-22 22:02 UTC, Jalleo commented on DS13/code/modules/EMH/EMH.dm
> +/obj/machinery/emh_emitter/process()
Change it so the START_PROCESS and STOP_PROCESS are called to begin and stop when a EMH moves into this emitter or moves out(leaves to go to another emitter) [Literally one proc can do both of that with use of a single var or something to control it].

2019-01-24 09:29 UTC, spookydonut requested changes

2019-01-24 09:29 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	if(user.client)
Change this to early returns

2019-01-24 09:29 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	if(istype(user, /mob/living/carbon/human/species/holographic)) //Allow them to jump to different locs.
change this to early return

2019-01-25 14:01 UTC, spookydonut requested changes
please let me know if you need help with early returns

2019-01-25 14:01 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	if(ID && istype(ID))
```suggestion
	if(!ID || !istype(ID))
		return
```
early return all this

2019-01-25 14:01 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +		if(check_access(ID))
```suggestion
		if(!check_access(ID))
			return
```

2019-01-25 14:01 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +			if(question == "yes")
```suggestion
			if(question == "no")
				return
```

2019-01-25 14:01 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	. = ..()
```suggestion
	return ..()
```
may as well just return ..() since its the end of the proc

2019-01-25 14:01 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +		if(question == "yes")
```suggestion
		if(question == "no")
			return
```

2019-01-25 18:57 UTC, spookydonut submitted a review, later dismissed

2019-01-25 18:57 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	if(check_access(ID))
```suggestion
	if(!check_access(ID))
		return
```

2019-01-25 18:57 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +		if(question == "no" || !question)
```suggestion
		if(question != "yes")
```

2019-01-25 18:57 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	if(get_dist(emh, src) >= range || emh.z != z) //Out of range, try find the EMH another emitter or tele him back to us.
errrrrrrrrrrrleeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee reeeeeeeeeeeeettttttttttuuuuuuuuuuuu

2019-01-25 18:57 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	if(emh.client && emh.mind) //Hitchiking off of this until I can make a new jobban
early return this

2019-01-25 18:57 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +		emh.alpha = 255
this should be in `/mob/living/carbon/human/species/holographic` init or postspawn or however your species code works

2019-01-25 18:57 UTC, spookydonut commented on DS13/code/modules/EMH/EMH.dm
> +	var/datum/job/captain/J = new/datum/job/captain
make a job for the emh

2019-01-30 16:09 UTC, Jalleo reviewed
Almost there. The processing changes are very adequate.

2019-01-30 16:09 UTC, Jalleo commented on DS13/code/modules/EMH/EMH.dm
> +	var/datum/job/captain/J = new/datum/job/captain
Agreed it would be better to maintain that way.

2019-01-30 16:09 UTC, Jalleo commented on code/__DEFINES/role_preferences.dm
> +#define ROLE_EMH				"Emergency Medical Hologram" //DeepSpace 13 - EMH
We probably should try and work out a system so our roles are separated out into another tab from the TG roles. Primarily so its quicker to phase out. (Out of scope from this PR just resolve this comment after reading it)

2019-01-30 16:09 UTC, Jalleo commented on DS13/code/modules/EMH/EMH.dm
> +	<h2> You are an emergency medical hologram! </h2>\
See the setup with AI laws and how it can be set config wise. We should use that to have this info below.

2019-01-30 16:09 UTC, Jalleo commented on DS13/code/modules/EMH/EMH.dm
> +		START_PROCESSING(SSfastprocess, closest)
stop processing the src here as well

2019-01-30 16:09 UTC, Jalleo commented on DS13/code/modules/EMH/EMH.dm
> +		if(saveme)
How will you confirm that the saveme ISNT this one or another that is about to be destroyed?

2019-01-30 16:09 UTC, Jalleo commented on DS13/code/modules/EMH/EMH.dm
> +/obj/machinery/emh_emitter/Initialize()
Now create a Global list specifically for the emh emitters (Or use the camera network if we are not using the SS13 camera objects/create a subsection of the camera network global for the EMH network)
Along with working out how to use the world camera_sort proc for the list.
The reason for using that proc is to make it so each emitter has a number after it so you know which one it is in that area. The second aspect is that it sorts the list into each area so its easier to navigate.

2019-01-30 16:12 UTC, Jalleo approved these changes
SCREEEEEEEEEEEEEEEE. KMC fucked up and we cant test borgs due to flipping bad setup locally. SCREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

2019-01-30 16:12 UTC, merged