Medicalrework
DDMers/Deep-Space-13 pull request #100
Opened 2019-05-31 13:14 UTC by Zargserg

Moderate rework for medical, focusing on chemicals.

>Changing names to Star Trek counterparts.
>Readding Inaprovaline as a stabilizing medicine.
>Dermaline and Terakine need Kelotane and Bicaridine for production (Replacing Oxygen and Carbon in the recipes)
>Bicaridine and Kelotane can mend moderate injuries but are ineffective for severe and life-threatening injuries. 
>Terakine and Dermaline are effective in treating severe injuries as well as moderate.
>Brute packs and ointment are now only capable of healing minor damage (5pts each).
>Saline-solution does not heal anymore and will compromise breathing if overdosed.

There may be further changes, especially to bleeding and blood-recovery later.

2019-06-08 13:00 UTC, alexkar598 commented
The blood related changes will have to be done in another PR for modularization.This PR shall only contain tweaks to chems(brute packs changes are fine)

2019-06-08 13:04 UTC, Zargserg commented
Alrighty! I shall focus then on meds, will make an ingame document later for it and then poke KMC.

Right now though I'm on holidays and have no proper rig to work with so stuff has to wait.

2019-06-08 13:05 UTC, alexkar598 commented
Please list all name changes in your PR body.

2019-06-08 13:06 UTC, alexkar598 requested changes
Please list all chem name changes in your PR body

2019-06-08 13:15 UTC, alexkar598 requested changes

2019-06-08 13:15 UTC, alexkar598 commented on code/game/objects/items/stacks/medical.dm
> +	heal_brute = 10
Misdocumented change

2019-06-08 13:15 UTC, alexkar598 commented on code/game/objects/items/stacks/medical.dm
> +	heal_burn = 10
Misdocumented change

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	color = "#00ffb0" // rgb: 200, 165, 220
Why?

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	color = "#eb7327"
Why?

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	if(M.getFireLoss() > 25)
Document exact number in PR body

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	description = "Can be used as a temporary blood substitute. Overdosing causes displacement of regular blood oxygen."
Please document that saline still heals blood lost

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	if(M.getBruteLoss() > 25)
Undocumented changed

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	M.adjustOxyLoss(-0.5*REM, 0)
Please list all properties of inaprovaline in the PR body

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	color = "#fd0000"
Why

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +		M.adjustBruteLoss(-2*REM, 0)
State exact number in PR body

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
> +	color = "#05a728"
Why?

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/reagents/medicine_reagents.dm
>  /datum/reagent/medicine/inaprovaline
Dual definition of inaprovaline

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/reagents/chemistry/recipes/medicine.dm
> +	required_reagents = list("inaprovaline" = 1, "carbon" = 1)
Undocumented change

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/surgery/bodyparts/bodyparts.dm
> +		if((get_damage(TRUE) >= max_damage) || (owner.has_trait(TRAIT_EASYLIMBDISABLE) && (get_damage(TRUE) >= (max_damage * 0.45)))) //Easy limb disable disables the limb at 40% health instead of 0%
Undocumented change

2019-06-08 13:15 UTC, alexkar598 commented on code/modules/surgery/bodyparts/robot_bodyparts.dm
> +	max_damage = 15
Undocumented change

2019-06-08 13:17 UTC, alexkar598 commented
@Zargserg big dummy me,meant atomization not modularization

2019-06-16 18:07 UTC, ben10083 commented
is this still being worked on?

2019-07-01 12:32 UTC, alexkar598 commented
Closing next week if no activity until then

2019-07-05 00:50 UTC, closed without merging

2019-07-05 08:42 UTC, Zargserg commented
> Closing next week if no activity until then

Yeh, I simply have lost interest in SS13 at the time being.
Stuff's been a tad too rough and I eventually forgot about the pull-request as well.