Columbia Escort Frigate
DDMers/Deep-Space-13 pull request #104
Opened 2019-06-04 01:50 UTC by Vasily2013

This heavily modified Kelvin Class ship is meant to either supplement a main battle fleet in the post Wolf 359 Alpha Quadrent, or to serve as a primary escort or security ship for a convoy or escort. The  Columbia boasts four decks with all required necessities for a Starfleet ship of war while still enjoying some of the creature comfort and research capability of her larger or more antiquated counterparts. It even contains a stigma not frequently found on other starfleet ships. A cloning bay, although rarely used, does exist and is available for use to those crew members who are not revolted by the thought.

https://gyazo.com/b9f0fbea161555f24c374f45baac6c2c

https://gyazo.com/a5a15a84e413eb64f5e89eba28f846e0

https://gyazo.com/f88f60489fd52b4163e0aef96bdd63ec

https://gyazo.com/fd311d610bf3718511ffb26c6fae1444

2019-06-08 12:58 UTC, alexkar598 commented
Note that you can integrate images in your post by using the syntax ``![](link)`` example: 

``![](https://i.gyazo.com/b9f0fbea161555f24c374f45baac6c2c.png)``

I changed it for you this time

2019-06-12 05:14 UTC, crossedfall commented on DeepSpace13.dme
> -#include "code\modules\a
This file should be removed from the PR unless actual changes to the DME are needed.

2019-06-13 00:34 UTC, crossedfall commented on DeepSpace13.dme
> -#include "code\modules\a
Resolved now.

2019-06-15 02:53 UTC, ben10083 commented
For the deck with the bridge, I recommend moving everything down one or two (area below the lifts) to allow for a passage between the sides of the deck without requiring bridge access.

2019-06-15 10:38 UTC, alexkar598 commented
Is this PR still a WIP or is it ready for review?

2019-06-15 15:17 UTC, Vasily2013 commented
> For the deck with the bridge, I recommend moving everything down one or two (area below the lifts) to allow for a passage between the sides of the deck without requiring bridge access.

For deck 1 the primary role is bridge, AI, and t-comms. (Thinking of that I'll be adding CE access to the AI doors so CE can get to t-comms.) If someone needs to be able to access the exact same equipment on the other side of deck 1 and doesn't have bridge access they can go around via deck 2.

2019-06-15 15:18 UTC, Vasily2013 commented
> Is this PR still a WIP or is it ready for review?

It's ready for review, but the idea of a map that isn't a Work in progress is a myth. Any tweaks from here on out will be covered in fairly good detail through the commit logs. See above reply to Ben for details on what will probably be the next commit.

2019-06-26 08:16 UTC, Michael-Ashfield commented
I like this, seems like an interesting and fun ship, I just feel theres abit too much carpet really. I imagine areas like engineering would have some more fitting floor, such as tiling, since it is meant to be a messy, possibly dangrous, working area. This also goes for the kictchen and external airlocks, which don't seem suitable for nice carpet. Also different floors add more variety to the look and feel of different areas of the ship.

2019-06-30 12:28 UTC, francinum requested changes
Missing blobstart, carpspawn landmarks.

2019-06-30 20:23 UTC, LordWalnut commented
@Michael-Ashfield This is a federation starship... most of it has fancy carpet down

2019-06-30 23:37 UTC, Vasily2013 commented
> Missing blobstart, carpspawn landmarks.

Intended.

2019-07-03 18:36 UTC, Harry-Jubilee approved these changes
All looks fantastic :)

2019-07-03 20:16 UTC, Kmc2000 approved these changes
No other maps have those landmarks

2019-07-03 20:17 UTC, merged

2019-07-06 06:32 UTC, francinum commented
@Kmc2000 that sounds like an issue with the other maps. not this one.