Adds turbolifts!
DDMers/Deep-Space-13 pull request #13
Opened 2019-01-22 20:24 UTC by Kmc2000

:cl: Kmc2000
add: Added turbolifts! Suffer not a crewman to have to climb up ladders no more.
/:cl:

https://i.gyazo.com/0c9beea615c934372584d0cb7ec38208.mp4

This is gonna need a lot of code review. I did some things for the sake of getting a prototype that are sorta messy.

Mapping these in is real simple, see documentation in the file.

They and their surrounding turfs are indestructible.. -- for now. It'd be mega immersion breaking if you could just break the walls down y'know?

2019-01-22 21:59 UTC, Jalleo submitted a review, later dismissed
See comment for details. I wont review anything more than that for now.

2019-01-22 21:59 UTC, Jalleo commented on DS13/code/modules/turbolift/turbolift.dm
> +/obj/structure/turbolift/process()
DENIED.

Use a system like the teleporter hub where it all connects up and one of them handles all this shit. Along with using a timer to know when they all unbolt.

2019-01-25 14:39 UTC, spookydonut requested changes
erlireetern

2019-01-25 14:39 UTC, spookydonut commented on DS13/code/modules/turbolift/turbolift.dm
> +	if(is_controller)
```suggestion
	if(!is_controller)
		return
```

2019-01-25 14:39 UTC, spookydonut commented on DS13/code/modules/turbolift/turbolift.dm
> +	if(S)
```suggestion
	if(!S)
		return
```

2019-01-25 18:47 UTC, spookydonut approved these changes

2019-01-25 18:55 UTC, merged