Docking mechanic + Star Trek theming
DDMers/Deep-Space-13 pull request #18
Opened 2019-01-27 18:00 UTC by Kmc2000

Somewhat inspired by:
https://tgstation13.org/phpBB/viewtopic.php?f=9&t=18948&p=430524&hilit=gamemode+bounty#p430524

Ships will now dock with the station. These can either be positive encounters or negative ones. I have not yet added the customs system where you can reject ships as this is an alpha.

Proceedure:
Announcement made, players are offered spawns on the ships.
Security scans the ship with the transporter and beams down people to search it if needs be.
If all is well, security will beam up the crews from the ships and they can join the round.

In total, there are 4 ship spawns per round at 3-10 minute intervals (random). Currently this encompasses every spawn for testing purposes.
There are 11 player spawns available within these 4

Other things:

Tazers are gone. They've been replaced with phasers and custom special FX. The HOS gets a phaser rifle which is super strong.
Klingons are now in the game! (Not roundstart chooseable yet)
aiannounce.ogg has been changed into a star trek themed version to avoid mass file changes.
Removed the buggy pockets from trek jackets

Feedback and event ideas welcome

:cl: Kmc2000
add: Ships will now dock with the station! This can either be a really good thing or a really bad thing.
/:cl:

2019-01-28 01:39 UTC, spookydonut commented
Atomize dis

2019-01-28 08:25 UTC, Kmc2000 commented
This PR needs all of these components, especially the species

2019-01-28 18:57 UTC, Jalleo requested changes
PR the projectile and all of that separately to quickly merge that sooner than this. I want to properly review the docking mechanic code but I don't want to delay this other stuff which is suitable to add in sooner.

2019-01-28 18:57 UTC, Jalleo commented
I also fixed your spelling errors in the PR text.

2019-01-28 23:07 UTC, Kmc2000 commented on DS13/code/modules/borg/conversion.dm
> +/obj/item/borg_tool/afterattack(atom/I, mob/living/user, proximity)
Yeah what the shit is this I really need to fix this huh

2019-01-28 23:07 UTC, Kmc2000 commented on DS13/code/modules/borg/conversion.dm
> +/obj/structure/chair/borg/charging/process()
This also sucks

2019-01-30 09:48 UTC, Kmc2000 commented
This will need a mapmerge on CentCom.dmm

2019-02-06 20:53 UTC, Jalleo commented
This PR is Do not merge until the borg PR has been fully reviewed and merged.

2019-03-04 14:33 UTC, closed without merging