Atomizes darkmode pr
DDMers/Deep-Space-13 pull request #24
Opened 2019-02-06 20:46 UTC by Kmc2000

:cl: Kmc2000
add: Darkmode is now enabled by default. 
/:cl:

Atomization of: https://github.com/DDMers/Deep-Space-13/pull/23

2019-02-08 18:43 UTC, alexkar598 requested changes
Screenshots required for UI change :)

2019-02-08 18:48 UTC, alexkar598 requested changes
Post screenshot for UI change :)

2019-02-08 18:48 UTC, alexkar598 commented
Well fuck,sorry for double post

2019-02-08 18:54 UTC, Kmc2000 commented
https://camo.githubusercontent.com/ca7a41e7126437ba32be4fba024113d9c7d0d79e/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3337393534303030373437373833373832342f3534323830333734323233363437353431342f756e6b6e6f776e2e706e67

2019-02-08 18:56 UTC, Kmc2000 commented
How to approve my own PR ????

2019-02-08 19:01 UTC, Kmc2000 commented
https://cdn.discordapp.com/attachments/379540007477837824/543506734560575505/unknown.png

2019-02-08 19:04 UTC, alexkar598 submitted a review, later dismissed

2019-02-08 19:04 UTC, alexkar598 commented on code/modules/goonchat/browserassets/css/browserOutput.css
> +	background: #ECE3E3;
Chat color aint working

2019-02-08 19:04 UTC, alexkar598 commented on interface/skin.dmf
> +		pos = 5,420
Why the position change?

2019-02-08 19:20 UTC, Kmc2000 commented on code/modules/goonchat/browserassets/css/browserOutput.css
> +	background: #ECE3E3;
Intended

2019-02-09 11:52 UTC, Jalleo commented on code/modules/goonchat/browserassets/css/browserOutput.css
> +	background: #ECE3E3;
Its just slightly darker

2019-02-09 11:53 UTC, Jalleo approved these changes
We will want to make this a config pref for people.

2019-02-09 11:54 UTC, merged