Adds darkmode properly this time :tm:
DDMers/Deep-Space-13 pull request #32
Opened 2019-02-27 21:10 UTC by Kmc2000

If we rebase to /tg/ I'll re-port this myself

:cl: Kmc2000
add: Darkmode
/:cl:

![](https://cdn.discordapp.com/attachments/379540007477837824/550416977722605592/unknown.png)
(Hyperlink colour is now fixed)

2019-03-07 22:12 UTC, alexkar598 requested changes

2019-03-07 22:12 UTC, alexkar598 commented on interface/skin.dmf
> +		size = 595x20
why change the size of this?

2019-03-07 22:12 UTC, alexkar598 commented on interface/skin.dmf
> +		size = 80x20
why?

2019-03-07 22:12 UTC, alexkar598 commented on interface/skin.dmf
> -		size = 100x20
why did you change all the buttons size and position?

2019-03-08 21:03 UTC, Kmc2000 commented
Adding a pref for it. DNM

2019-03-09 18:11 UTC, merged