Adds cadets, vulcans, andorians + new door sprites + morale officer + new circuitboard sprites
DDMers/Deep-Space-13 pull request #39
Opened 2019-03-19 16:07 UTC by Kmc2000

https://cdn.discordapp.com/attachments/360878113959182337/557580640824983552/unknown.png
https://cdn.discordapp.com/attachments/360878113959182337/557568270379515916/unknown.png

:cl: Kmc2000
add: You can now play as Vulcans and Andorians
add: The clown is now more lore friendly
add: Circuitboards were resprited to be isolinear chips
/:cl:

2019-03-19 17:02 UTC, spookydonut commented
Atomise

2019-03-20 20:22 UTC, Jalleo commented on DS13/goonstation/airlocks.dm
> +	name = "Main Engineering"
EW

2019-03-20 20:23 UTC, Jalleo requested changes
All engineering doors will be named main engineering.... Why isnt Engineering good enough?

2019-03-21 17:59 UTC, Jalleo approved these changes
Someone else can confirm its fine or just merge it.

2019-03-21 18:05 UTC, merged