Adds a lightweight section31 operative as seen in 2cw's PR
DDMers/Deep-Space-13 pull request #77
Opened 2019-04-12 16:14 UTC by Kmc2000

![](https://cdn.discordapp.com/attachments/360877760580943873/566293639592935439/unknown.png)

:cl: 2cwldys
add: May or may not have added a section31 antag, which does not exist
/:cl:

This is a rework of #66 but more light-weight and with a few code fixes.

2019-04-12 19:14 UTC, 2cwldys commented
Glad to see it has some use!

2019-04-13 14:19 UTC, alexkar598 requested changes

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	SSticker.mode.traitors += owner
What if the mode is clings or extended

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	var/section31_outfit = /datum/outfit/section31
Useless var that removes to code readability,inline it

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	//Remove malf powers.
Um what?

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	SSticker.mode.traitors -= owner
See comment in on_gain

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	owner.special_role = null
Revoke code speak

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +
Code words are already given in on_gain

2019-04-13 14:19 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	back = /obj/item/storage/backpack/duffelbag/syndie
Syndicate duffel bag? Come on,is it ss13 now?

2019-04-13 17:06 UTC, alexkar598 commented on DS13/code/modules/antagonists/section31.dm
> +	new /obj/item/chameleon(src)
W-w-what?

2019-04-13 17:08 UTC, alexkar598 approved these changes
all abord the merge train

2019-04-13 17:09 UTC, merged